version: '3.5'
services:

  disciplinator:
    restart: unless-stopped
    image: disciplinator:latest
    container_name: disciplinator
    environment:
      RUST_LOG: info
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - disciplinator:/etc/disciplinator/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  disciplinator:
    name: disciplinator
