[package]
name = "driver"
version = "0.1.0"
authors = ["Mike Lubinets <public@mersinvald.me>"]
edition = "2018"

[dependencies]
headmaster = { path = "../headmaster" }
failure = "0.1.5"
reqwest = "0.9.5"
serde = { version = "1.0.84", features = [ "derive" ] }
serde_json = "1.0.34"
log = "0.4.6"
